name: django-pools-app
services:
  app:
    build:
      context: .
      args:
        DEV: true
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASSWORD=devpass
      - DB_HOST=db
    depends_on:
      - db

  db:
    image: postgres:17.0-alpine3.20
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpass
    ports:
      - "5432:5432"
    volumes:
      - dev-db-data:/var/lib/postgresql/data

volumes: 
  dev-db-data: